### ISSUE TITLE
Project progress

### ISSUE THREAD

**Issue by Retsediv** [skycoin/ledger-nano#3]
**Feature description**
Basic functional for BOLOS app

**Describe the solution you'd like**
The main high-level tasks: generate keypair, sign a transaction and send it back to the desktop companion app, simple user interface(like in similar apps)

**Possible implementation:**
- [x] Initialize repo and whole workflow #2 
- [x] App description, version, menu #9 
- [x] Public/private keys generation #4 
- [x] Creating the signature for transaction #10 
- [x] Key derivation
- [x] Text display
- [ ] Wrapper #21 
- [ ] Tests #20 
- [ ] Interaction with companion app
- [ ] Check for vulnerabilities
